- name: Example Module
  hosts: ubuntu
  become: true
  tasks:
    - name: 'Create user'
      user: 'name=leedonggyu shell=/bin/bash'

    - name: 'Add DNS server to resolv.conf'
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver 8.8.8.8'

    - name: 'Upload web directroy'
      synchronize:
        src: files/html
        dest: /var/www/html
        archive: true
        checksum: true
        recursive: true
        delete: true

    - name: 'Copy nginx conf file'
      copy:
        src: files/default
        dest: /etc/nginx/sites-enabled/default
        owner: '{{ansible_user}}'
        group: '{{ansible_user}}'
        mode: '0644'
      notify:
        - Restart Nginx

    - name: 'Ensure nginx service started'
      service:
        name: nginx
        state: started

  ## notify에 연결된 event를 기준으로 반응함...
  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
